package is.system.prompt.parser.analyzer;

public enum Token {


    NEW,DEL,MV,MVOFF,SCALE,LS,ALL,GROUPS,GRP,UNGRP,AREA,PERIMETER,CIRCLE,RECTANGLE,IMG,LEFT_PAR,RIGHT_PAR,COMA,NOT_VALID_CHAR,NOT_VALID_WORD,POSFLOAT,OBJ_ID,PATH,B_A_PATH,EOF
}
